### ISSUE TITLE
Clicking the down arrow icon to download an SVG doesn't work

### ISSUE THREAD

**Issue by kctuskey** [ionic-team/ionicons#885] opened 2020-09-17 13:45 UTC
After selecting an icon in Firefox 80.0.1 for MacOS 10.15.6 (Catalina), when the user clicks the down arrow icon to try to download the SVG in the modal that appears at the bottom of the screen, a spinning icon displays and the system hangs there.

After some troubleshooting, I realized that I had to click the text "SVG" to download the SVG instead of the down arrow icon.

The expected behavior is that the system wouldn't get stuck if I clicked the down arrow icon because that appears to be part of the same button as the word "SVG".

**Comment by cupcakearmy** [comment] 2021-07-20 11:46
Can confirm it does not work on firefox and safari, only chrome.

**Comment by liamdebeasi** [comment] 2023-12-14 19:18
Hi there,

Apologies for the delay. I tested this in Firefox 120 and Safari 17.1 and was unable to reproduce the reported behavior. It seems like this problem was resolved at some point, but this issue was never closed. I am going to close this, but please let me know if you are still running into this problem.

**Closed by liamdebeasi** 2023-12-14 19:18 UTC
Labels: triage
