### ISSUE TITLE
icon request: Weibo(Sina)

### ISSUE THREAD

**Issue by felotuik** [ionic-team/ionicons#1234] opened 2023-06-16 06:38 UTC
### Describe the Icon

Weibo(Sina) is a widely used app similar to Twitter, and we urgently need this icon.

### Links to Examples

https://cn.bing.com/images/search?q=weibo%20icon

**Comment by mapsandapps** [comment] 2023-06-16 12:02
Hi, thank you for the issue. I'm going to close this as a duplicate of #965.

**Closed by mapsandapps** 2023-06-16 12:02 UTC
Labels: triage
