### ISSUE TITLE
Error with Save icon

### ISSUE THREAD

**Issue by edu526** [ionic-team/ionicons#592] opened 2018-08-08 21:46 UTC
Hi.

I have a error with Save icon
<ion-icon name="save" text-right color="light"></ion-icon>

This show a key icon

### V 4.3.0
<a href="https://ibb.co/bzB41U"><img src="https://preview.ibb.co/nv3v89/Screenshot_6.png" alt="Screenshot_6" border="0"></a>
<a href="https://imgbb.com/"><img src="https://image.ibb.co/cVE2o9/Screenshot_7.png" alt="Screenshot_7" border="0"></a>

Thanks.

**Comment by eduardorossi** [comment] 2018-09-29 19:48
Hi, I'm with the same error mentioned above, but the version I'm using is 4.4.4

Team Ionic, could you fix this error?

**Comment by dantelent** [comment] 2018-11-22 10:47
In v4.4.7 the Save icon is a leaf

**Comment by jacargentina** [comment] 2019-03-12 00:28
Any news on this? Same problem here, having a key when i need a disk for saving!

**Comment by fortuneNext** [comment] 2019-03-21 14:40
Yeah, this is pretty annoying.... Leaf instead of disk.

**Comment by 3xpedia** [comment] 2019-07-26 20:50
Same issue here.
Quit annoying :/

**Comment by TomDoesbRUG** [comment] 2019-08-13 13:56
This is still an issue in v4.6 ...

**Comment by amandaejohnston** [comment] 2023-07-11 15:12
Looks like this has been resolved in the time since it was posted; icons are all displaying correctly when tested on my end using the latest version of Ionicons. If you're still running into this, please create a new issue and include a minimal reproduction. Thank you!

**Closed by amandaejohnston** 2023-07-11 15:12 UTC
Labels: triage
