### ISSUE TITLE
Ionicons on Microsoft Edge are misplaced about 32px to the bottom

### ISSUE THREAD

**Issue by NoCapDeveloper** [ionic-team/ionicons#734] opened 2019-10-27 21:47 UTC
Just create a box with flexbox centered ionicon. While it works perfectly in webkit-based browsers (perfectly centered on Opera, Chrome) it is always misplaced by consistent number of pixels to the bottom.

Chrome / Opera:
![bug1](https://user-images.githubusercontent.com/54031241/67642396-9a49e000-f90b-11e9-97b0-b5615cb5ea55.PNG)

Microsoft Edge:
![bug2](https://user-images.githubusercontent.com/54031241/67642400-a2a21b00-f90b-11e9-9093-42ffd0f17828.PNG)

It is a consistent bug not only with flexbox but it is always misplaced this way.

**Comment by amandaejohnston** [comment] 2023-07-26 14:28
Thanks for the issue! I'm unable to reproduce this on the latest version of Ionicons, so I'll go ahead and close this out. If you're still having trouble on the latest version, please open a new issue and include a minimal reproduction.

**Closed by amandaejohnston** 2023-07-26 14:28 UTC
Labels: triage
