### ISSUE TITLE
Icon set is non-usable on Android 8.1 devices with the latest Chrome Update

### ISSUE THREAD

**Issue by richardshergold** [ionic-team/ionicons#984] opened 2021-06-18 11:17 UTC
We’ve had a flood of recent complaints about our Ionic 5 / Capacitor app not working correctly on the Android devices running Android 8.1. I finally got hold of one of these devices today and from a factory reset (where the version of Chrome is 70.0.3538.110) our app works fine. But as soon as the app updates Chrome to the latest version (91.0.4472.101) the app behaves very strangely - some weird very glitchy things happen and the app is unusable.  

I narrowed it down to a problem with the ionic icon set.

(Other devices with later Android versions that are on 91.0.4472.101 appear to be working fine - so far)

See [here](https://forum.ionicframework.com/t/android-8-1-device-errors-after-updating-to-latest-chrome/211106) for more details and screenshots

**Comment by retoko** [comment] 2021-08-31 11:57
any updates?

**Comment by richardshergold** [comment] 2021-08-31 12:00
it is with the Chromium team

https://bugs.chromium.org/p/chromium/issues/detail?id=1222095

**Comment by retoko** [comment] 2021-08-31 12:17
Thanks, I watched this. But the problem is still not resolved either in the current version of chrome or in the beta version. The terms of the decision have not been presented, 2 months have passed.
Are there any workarounds? Just using a different icons library?

**Comment by richardshergold** [comment] 2021-08-31 12:29
Hopefully there will be a fix in Chrome soon.  We've got round it by hiding icons from 8.1 users in a temporary fix - not ideal in any way but it has made the app at least usable for them.

**Comment by liamdebeasi** [comment] 2021-11-23 23:19
Thanks for the issue. This seems to have been resolved in Chrome 96, so I am going to close this out.

**Closed by liamdebeasi** 2021-11-23 23:19 UTC
