### ISSUE TITLE
Logo request: X

### ISSUE THREAD

**Issue by nilaysarma** [ionic-team/ionicons#1333] opened 2024-02-09 18:27 UTC
Add the new Twitter logo X
![images (1).png](https://github.com/ionic-team/ionicons/assets/79686507/2c5f4234-7dc3-478a-9502-2e7a2389a56d)

**Comment by mapsandapps** [comment] 2024-02-09 18:44
Hi, thank you for your logo request. I'm going to close this as a duplicate of #1249

**Closed by mapsandapps** 2024-02-09 18:44 UTC
Labels: triage

**Comment by nilaysarma** [comment] 2024-02-09 18:50
> Hi, thank you for your logo request. I'm going to close this as a duplicate of #1249 

Oh, I didn't saw that. Can I get to know when the X logo will be added?
