### ISSUE TITLE
Missing Flutter Icon

### ISSUE THREAD

**Issue by chenasraf** [ionic-team/ionicons#1103] opened 2022-08-31 16:45 UTC
It's a really popular Framework, I think an icon should be added :) 

Something like this should do it: ([iconfinder link](https://www.iconfinder.com/icons/4691465/flutter_icon)):

![example](https://cdn4.iconfinder.com/data/icons/logos-brands-5/24/flutter-512.png)

I'll whip up an SVG if needed, but not sure what else is needed for a PR, so some general direction would be nice. I'd be happy to make a new version of the icon and add it where necessary.

**Comment by brandyscarney** [comment] 2022-09-27 22:06
Thank you for the issue, closing as a duplicate of #963

**Closed by brandyscarney** 2022-09-27 22:06 UTC
Labels: type: icon request
