### ISSUE TITLE
toggle-outline is wonky and not the same shape as toggle

### ISSUE THREAD

**Issue by quarfie** [ionic-team/ionicons#837] opened 2020-05-31 20:47 UTC
toggle-outline is wonky and not the same shape as toggle

**Comment by bensperry** [comment] 2020-06-24 15:13
Can you share a screenshot? I'm not seeing any issues with it.

**Comment by brandyscarney** [comment] 2022-09-29 21:06
Thanks for the issue! Closing due to a lack of reproduction. If you are still seeing problems with the latest version of Ionicons please create a new issue with a code reproduction.

**Closed by brandyscarney** 2022-09-29 21:06 UTC
Labels: triage
