### ISSUE TITLE
Telegram icon

### ISSUE THREAD

**Issue by erofex** [ionic-team/ionicons#495] opened 2017-07-10 22:01 UTC
please add telegram, thank you

**Comment by TiagoDanin** [comment] 2017-09-02 18:54
Duplicate #338

**Comment by bensperry** [comment] 2017-10-09 20:59
Will add this in to Ionicons v4 release!

**Comment by jsmsalt** [comment] 2018-05-29 01:13
@bensperry Why isn't there a Telegram icon yet?

**Comment by brandyscarney** [comment] 2019-01-16 23:21
Closing as duplicate of #338, thank you!

**Closed by brandyscarney** 2019-01-16 23:21 UTC
