### ISSUE TITLE
Random CORS Issue

### ISSUE THREAD

**Issue by bswank** [ionic-team/ionicons#692] opened 2019-05-22 14:31 UTC
I'm seeing a random issue with CORS blocking my requests. If I refresh my site 10-20 times in a row I typically see the issue at least once, and now I've seen it in production for the first time. Basically, I pull in ion-icons through unpkg.com and see the following error:

```
Origin https://new.thegospelfund.com is not allowed by Access-Control-Allow-Origin.
```

This may also be related to #674 and #570 but not sure. Check out my most recent Sentry error: https://sentry.io/share/issue/cbfc81e895b04bd8a8187e68d44f40cf/

**Comment by viapek** [comment] 2019-08-28 13:37
Giving CORS error on a single desktop but not experienced anywhere else (as yet). I have tried to find a setup where this is reproducible but so far no luck.

The reason I am posting fr help so early in my trouble shooting is that the error tells me that the origin and redirect from are the same domain but then says CORS error.

The site is hosted on firebase and all is served by the same firebaseapp.com domain. The only variation is for database access which is handled with angularfire.

All is working fine on the problem device except the icons :/ If anyone has any suggestions on where I can look next, I am humbly all ears

Thanks
![Error-masked](https://user-images.githubusercontent.com/13717661/63860353-ea77f500-c9e3-11e9-8490-133b4c137529.jpg)

**Comment by amandaejohnston** [comment] 2023-08-31 14:52
Thanks for the issue! I know it's been a while, but I'm going to close this due to lack of a reproduction. Normally I would ask for one first, but due to the age of this issue I'm unsure if it's still being monitored.

If this is still a problem in the latest version of Ionicons, I would recommend first asking on the [Ionic forums](https://forum.ionicframework.com/) or [Discord server](https://discord.com/invite/UPYYRhtyzp) since it sounds like the problem may be in the app's configuration rather than a bug in Ionicons. If it does turn out to be a bug though, please open a new issue here and include a minimal reproduction app.

**Closed by amandaejohnston** 2023-08-31 14:52 UTC
Labels: triage
