### ISSUE TITLE
Where is the icon font for Ionicons 5?

### ISSUE THREAD

**Issue by dwilches** [ionic-team/ionicons#992] opened 2021-07-20 21:19 UTC
I'm migrating from ion-icons 2 to 5, so I'm looking into what this line's replacement should be:

    <link rel="stylesheet" type="text/css"
          href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"/>

But there is no link for using the Iconicons Font in the readme. Previously, for [version 4](https://ionic.io/ionicons/v4/usage) I see there were the following instructions:

     To embed the Ionicons font icon, copy this code into the <head> of the HTML document.
     <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">

But I'm not seeing the equivalent of that for ionicons 5, as that text was removed [in this commit](https://github.com/ionic-team/ionicons/commit/65e1cfabfe5b17da4812968b4f73d7130f786893).

How can I use ionicons without the Web Component?

Thanks.

**Comment by dkniffin** [comment] 2021-09-03 19:35
This is a duplicate of https://github.com/ionic-team/ionicons/issues/772

**Comment by liamdebeasi** [comment] 2021-11-23 23:17
Hey there,

With Ionicons 5 we moved to using SVGs instead of icon fonts. This reason for this is the icon font required developers to bundle several megabytes of font data with every app, even if they were not using all the icons. With SVGs, developers can include only the icons they need to use in their app. At the moment, we do not have plans to re-introduce the icon font. Thanks for understanding!

**Closed by liamdebeasi** 2021-11-23 23:17 UTC
