### ISSUE TITLE
Spotify Icon 

### ISSUE THREAD

**Issue by RaiderXSkull** [ionic-team/ionicons#1041] opened 2022-01-29 14:27 UTC
Can you add a spotify logo we can use?

Thanks
Aditya Kumar

**Comment by ChooseGoose001** [comment] 2022-02-15 11:04
Hello! I would also like to request a Spotify logo - the icons are glorious :)

**Comment by GlxryX** [comment] 2022-03-13 18:47
A Spotify logo would be nice.

**Comment by ImLowly** [comment] 2022-06-10 17:35
This has been requested for a long time now.

**Comment by brandyscarney** [comment] 2022-09-27 22:04
Thanks for the issue, closing as a duplicate of #478

**Closed by brandyscarney** 2022-09-27 22:04 UTC
Labels: type: icon request
