### ISSUE TITLE
[Website] Download: Icons sometimes not loading or freezes the browser.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionicons#901] opened 2020-11-04 18:10 UTC
Downloading icons on https://ionicons.com/ is a gambling game. 
![demo](https://user-images.githubusercontent.com/60390085/98151698-e3465400-1ed0-11eb-8a96-89dfeda73059.gif)

Cases:
- Works like expected.
- Long loading before download starts. (Loading Animation)
- Long loading before download starts and freezes the browser for seconds. (window not responding)
- Infinite loading animation. Never downloads. 

For some cases there are errors on console:

```
Access to fetch at 'https://unpkg.com/ionicons@5.2.3/dist/svg/code-working.svg' 
from origin 'https://ionicons.com' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
But on page reload you have another change to download. And sometimes it works.

Windows 10 64bit Pro, Latest Chrome.

**Comment by liamdebeasi** [comment] 2023-12-14 19:19
Hi there,

Apologies for the delay. I tested this in Firefox 120 and Safari 17.1 and was unable to reproduce the reported behavior. It seems like this issue was resolved at some point, but this issue was never closed. I am going to close this, but please let me know if you are still running into this problem.

**Closed by liamdebeasi** 2023-12-14 19:19 UTC
Labels: triage
