### ISSUE TITLE
Telegram Icon

### ISSUE THREAD

**Issue by Arkky97** [ionic-team/ionicons#1055] opened 2022-03-31 12:44 UTC

**Comment by mmendozacl** [comment] 2022-04-18 00:30
There is no telegram icon

**Comment by sam-yi** [comment] 2022-04-26 20:44
Just use the paper-plane icon.  It's almost identical.

<ion-icon name="paper-plane"></ion-icon>

**Comment by brandyscarney** [comment] 2022-09-27 22:01
Thanks for the issue, closing as a duplicate of #1023

**Closed by brandyscarney** 2022-09-27 22:01 UTC
Labels: type: icon request
