### ISSUE TITLE
icon request:  cookies

### ISSUE THREAD

**Issue by IsaqueCar** [ionic-team/ionicons#1370] opened 2024-04-21 15:40 UTC
### Describe the Icon

what about a cookie icon for a terms and conditions page?(cookies page)

### Additional Information

context of this icon request: im using ionicons for a project and i need a icon for the cookies page

**Comment by liamdebeasi** [comment] 2024-04-30 20:10
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/822.

**Closed by liamdebeasi** 2024-04-30 20:10 UTC
Labels: triage
