### ISSUE TITLE
Address Book icon?!

### ISSUE THREAD

**Issue by erikvlarsson** [ionic-team/ionicons#1071] opened 2022-06-03 19:42 UTC
Would love an address book icon, please!

**Comment by erikvlarsson** [comment] 2022-06-03 19:44
Existing issue: https://github.com/ionic-team/ionicons/issues/920

**Comment by brandyscarney** [comment] 2022-09-27 15:54
Closing as a duplicate of #920, thank you!

**Closed by brandyscarney** 2022-09-27 15:54 UTC
