### ISSUE TITLE
motorcycle icon

### ISSUE THREAD

**Issue by zhangleijie** [ionic-team/ionicons#1079] opened 2022-06-27 17:05 UTC
![image](https://user-images.githubusercontent.com/10412168/175996502-5d22f890-fe7f-47eb-8caf-96ac9977f592.png)

No motorcycle icon here.

**Comment by brandyscarney** [comment] 2022-09-27 17:08
Closing as a duplicate of #403, thank you!

**Closed by brandyscarney** 2022-09-27 17:08 UTC
Labels: type: icon request
