### ISSUE TITLE
icon request: twitter-x

### ISSUE THREAD

**Issue by utybe-cpu** [ionic-team/ionicons#1283] opened 2023-09-30 08:10 UTC
### Describe the Icon

The x icon should be added as the twitter icon is outdated

**Comment by mapsandapps** [comment] 2023-10-02 14:30
Hi, thanks for the icon request. I'm going to close this as a duplicate of #1249

**Closed by mapsandapps** 2023-10-02 14:30 UTC
Labels: triage

**Comment by utybe-cpu** [comment] 2023-10-02 15:46
You guys should work on it
