### ISSUE TITLE
icon request: Nuxt

### ISSUE THREAD

**Issue by christophdubach** [ionic-team/ionicons#1146] opened 2022-11-18 13:11 UTC
### Describe the Icon

The official Nuxt 3 logo

### Links to Examples

https://nuxt.com/design-kit

### Additional Information

Since there’s an Ionic integration for Nuxt now, we need the corresponding icon.
https://ionic.nuxtjs.org

**Comment by mapsandapps** [comment] 2023-08-16 17:34
Thank you for the request. I'm going to close this as a duplicate of #1009

**Closed by mapsandapps** 2023-08-16 17:34 UTC
Labels: type: icon request, icon type: logo
