### ISSUE TITLE
No pound sign icon ?

### ISSUE THREAD

**Issue by lonalovegood1** [ionic-team/ionicons#491] opened 2017-06-03 19:54 UTC
I never thought i would come across this.
There is all the currency signs but no GBP £ sign. That's weird. Please consider sorting this out.

Thanks

**Comment by bensperry** [comment] 2017-10-09 20:25
Thanks, good catch. Will be added in v4.

**Comment by stobasan** [comment] 2019-02-21 12:21
Hi @bensperry, I just did a search for a pound icon in the Ionicons 4.4.4 and didn't get any results.
[https://imgur.com/a/kSqnjXk](url)

Can you please share when the pound icon will be added?

**Comment by MaxwellKeeble** [comment] 2020-06-20 15:06
It'd be good to add £ as GBP, it's a major world currency. There is an open pull request from 2015 to a much older version of ionicons - [https://github.com/ionic-team/ionicons/pull/248](https://github.com/ionic-team/ionicons/pull/248)- would it be possible to use the SVG provided in that?

**Comment by amandaejohnston** [comment] 2023-05-25 19:32
Thank you for the request. I'm going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/376.

**Closed by amandaejohnston** 2023-05-25 19:32 UTC
Labels: type: feature request, type: icon request
