### ISSUE TITLE
Patreon icon

### ISSUE THREAD

**Issue by MosqitoTorpedo** [ionic-team/ionicons#1104] opened 2022-09-05 03:34 UTC
Please add a patreon icon

**Comment by InfoBlock** [comment] 2022-09-08 17:06
Just wanted to suggest the same thing!

**Comment by harshsiri110** [comment] 2022-09-26 10:28
I am adding an SVG file for the [Patreon](https://www.patreon.com/) icon.

**Comment by brandyscarney** [comment] 2022-09-27 22:06
Thanks for the issue, closing as a duplicate of #397

**Closed by brandyscarney** 2022-09-27 22:06 UTC
Labels: type: icon request
