### ISSUE TITLE
icon request: Kaggle

### ISSUE THREAD

**Issue by Dongli99** [ionic-team/ionicons#1282] opened 2023-09-25 00:23 UTC
### Describe the Icon

I didn't find the icon of Kaggle.
Please consider to add it. 
Thanks.

### Links to Examples

https://www.iconfinder.com/icons/4373210/kaggle_logo_logos_icon

**Comment by mapsandapps** [comment] 2023-09-25 12:47
Hi, thanks for the icon request. I'm going to close this as a duplicate of #1005.

**Closed by mapsandapps** 2023-09-25 12:47 UTC
Labels: triage
