### ISSUE TITLE
Nintendo Icon

### ISSUE THREAD

**Issue by OGluffy** [ionic-team/ionicons#1017] opened 2021-11-05 06:26 UTC
I was doing good on building an app with you all till I needed the logo for Nintendo and it wasn't there maybe just make a square with a long oval in it to make up for it. I just ended up using the controller logo to compensate.

**Comment by OGluffy** [comment] 2021-11-05 06:28
or do the Nintendo switch icon, because that is the one I was actually looking for, and that is why I just settled for the controller icon?

**Comment by brandyscarney** [comment] 2022-09-27 22:04
Thanks for the issue, closing as a duplicate of https://github.com/ionic-team/ionicons/issues/936

**Closed by brandyscarney** 2022-09-27 22:04 UTC
Labels: type: icon request
