### ISSUE TITLE
setting the stroke color

### ISSUE THREAD

**Issue by noorbakerally** [ionic-team/ionicons#784] opened 2020-02-18 12:38 UTC
I am using the icon people-outline using the HTML:
`<ion-icon name="people-outline" class="overviewIcon" style="color: blue;"></ion-icon>`

The color remains black even with the style. How can I change the border color or the fill color of the icon ?

**Comment by andreas-aeschlimann** [comment] 2020-02-19 00:56
I can confirm this issue in my Angular project.

**Comment by aecvargas** [comment] 2020-02-21 15:01
I can also confirm that I am having this issue in my ionic application project.

`  <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>`

Some icons seem to work fine but I noticed it when an icon was missing from a page and it turns out that icon had been deleted/renamed so I picked a similar icon to replace it with, attaching the same class to it.

`<ion-icon class="arrow" name="chevron-back"></ion-icon>`

```
ion-icon.arrow {
    color: var(--ion-color-default) !important;
    vertical-align: middle;
}
```

It's odd that some icons work as normal and that it was also working before I started using the new version. Would really appreciate a fix on this ASAP.

**Comment by andreas-aeschlimann** [comment] 2020-02-21 17:20
Yep...

This issue is probably a duplicate of #778. You can use the CSS property filter to invert the color to white, at least.

**Comment by streamliner18** [comment] 2020-03-08 21:41
Need developer attention on this!! Seems like many SVG icons have hard-coded stroke colors which is really annoying..

**Comment by zenorocha** [comment] 2020-03-09 00:41
Same here, I can't use it because of this :(

**Comment by peterpeterparker** [comment] 2020-03-15 08:50
The problem is the following I think: the outline icons, at least the one I checked, have path defined with fixed `stroke:#000;`, therefore they are always rendered black.

These should probably be modified with `stroke:currentColor;`, if I'm not wrong.

I've provided a PR #805 to fix this issue.

**Comment by boradakash** [comment] 2020-04-08 14:42
Agree with @peterpeterparker . There are few icons with `stroke:#000` because of which the style on ion-icon is not working.

**Comment by hades200082** [comment] 2020-04-18 09:40
#817 also references this

**Comment by Perdixo75** [comment] 2020-08-06 18:06
Try this :
```
[ionicons] Deprecated script, please remove: <script src="https://unpkg.com/ionicons@5.1.2/dist/ionicons.js"></script>
To improve performance it is recommended to set the differential scripts in the head as follows:
<script type="module" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule="" src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"></script>
```

**Comment by aPixelInSpace** [comment] 2020-08-13 18:47
Thank you Perdixo75. That fixed the issue for me.

**Comment by Rezaul-karim-pstu** [comment] 2020-09-27 02:22
thanks Perdixo75. It works

**Closed** 2020-10-06 16:12 UTC
