### ISSUE TITLE
heart-half not loading

### ISSUE THREAD

**Issue by jungalwala** [ionic-team/ionicons#675] opened 2019-03-19 21:24 UTC
When I try and load the icon 'heart-half' I get what looks like a missing-icon icon (see below).

![Ionic App 2019-03-19 17-21-34](https://user-images.githubusercontent.com/1099499/54642662-88e25080-4a6b-11e9-924e-5b09253608b6.png)

I request the icon as follows:
`<ion-icon name="heart-half"></ion-icon>`

I am running ionicons 4.5.5

Ionic:
   ionic (Ionic CLI)  : 4.12.0 (/Users/jfj/.nvm/versions/node/v7.10.1/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.4
   @ionic/app-scripts : 3.2.3

Cordova:
   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.0.0, browser 5.0.3, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic 5.2.7, cordova-plugin-ionic-webview 2.3.1, (and 8 other plugins)

System:
   Android SDK Tools : 26.1.1 (/Users/jfj/Library/Android/sdk)
   NodeJS            : v7.10.1 (/Users/jfj/.nvm/versions/node/v7.10.1/bin/node)
   npm               : 5.7.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.1 Build version 10B61

**Comment by amandaejohnston** [comment] 2023-07-11 15:21
Looks like this has been resolved in the time since it was posted; icons are all displaying correctly when tested on my end using the latest version of Ionicons. If you're still running into this, please create a new issue and include a minimal reproduction. Thank you!

**Closed by amandaejohnston** 2023-07-11 15:21 UTC
Labels: triage
