### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by amitthecoder** [ionic-team/ionicons#1231] opened 2023-06-15 06:51 UTC
### Describe the Icon

Telegram icon

### Links to Examples

[Flaticon](https://www.flaticon.com/free-icons/telegram)

**Comment by mapsandapps** [comment] 2023-06-15 12:51
Hi, thank you for the icon request. I'm going to close this as a duplicate of #338.

**Closed as not planned by mapsandapps** 2023-06-15 12:51 UTC
Labels: triage
