### ISSUE TITLE
icon request: 

### ISSUE THREAD

**Issue by yavuzakyazici** [ionic-team/ionicons#1324] opened 2024-01-24 13:12 UTC
### Describe the Icon

I guess everyone is familiar with PDF icons

### Links to Examples

https://www.flaticon.com/free-icons/pdf

**Comment by amandaejohnston** [comment] 2024-01-24 15:16
Thank you for the request. I'm going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/690.

**Closed by amandaejohnston** 2024-01-24 15:16 UTC
Labels: triage
