### ISSUE TITLE
[bug] ion-icon is not rendering with databinding [Ionic 5-rc3]

### ISSUE THREAD

**Issue by marcelmedina** [ionic-team/ionicons#765] opened 2020-02-05 23:47 UTC
I am trying to dynamically associate images to ion-icon markdowns, but it doesn't work.

```
<ion-icon [name]="favouriteIcon" (click)="toggleFavourite()"></ion-icon>
```
favouriteIcon is a string that receives the name of the icon.

```
public favouriteIcon: string;
```

It renders nothing.

**Comment by kwiat1990** [comment] 2021-04-02 14:03
It's already a year since the question was asked and right now I have the very same problem - I'm trying to bind the name to a dynamic value, which comes from API but the icon won't be rendered and there is an error in the console: `https://unpkg.com/ionicons@5.0.0/dist/ionicons/svg/instagram.svg`.

I'm using Sapper and my code look something like this:
```
// iconCode is a string, e.g. "instagram"
<ion-icon name={iconCode} />
```

**Comment by liamdebeasi** [comment] 2024-03-21 23:00
Thanks for the report and apologies for the delay. There's not a lot of information regarding the issue you are encountering, so I am going to close this. If you are still running into this please feel free to open a new issue and include a reproduction.

**Closed by liamdebeasi** 2024-03-21 23:00 UTC
Labels: triage
