### ISSUE TITLE
No icon for Houzz?

### ISSUE THREAD

**Issue by flaxton** [ionic-team/ionicons#462] opened 2017-02-13 00:53 UTC
Houzz is a large social media site used by home designers and contractors, for example Kitchen and Bath projects.

Font Awesome has an icon for it, called: houzz

Ionicons needs to add it.

Their website is just houzz.com

Thanks!

Fred

**Comment by bensperry** [comment] 2017-10-09 21:02
Will add to v4 release!

**Comment by brandyscarney** [comment] 2019-01-16 23:31
Closing as a duplicate of #423. Please track this issue there, thanks!

**Closed by brandyscarney** 2019-01-16 23:31 UTC
Labels: icon: request, type: feature request
