### ISSUE TITLE
icon request: It would be very nice to have a PDF icon with PDF download icon

### ISSUE THREAD

**Issue by yavuzakyazici** [ionic-team/ionicons#1323] opened 2024-01-24 13:11 UTC
### Describe the Icon

I guess exryone is familiar with PDF icon :)

**Comment by amandaejohnston** [comment] 2024-01-24 15:16
Thank you for the request. I'm going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/690.

**Closed by amandaejohnston** 2024-01-24 15:16 UTC
Labels: triage
