### ISSUE TITLE
latest ion-icons not working with ionic5 on uiwebview and wkwebview

### ISSUE THREAD

**Issue by rashmendis** [ionic-team/ionicons#831] opened 2020-05-14 14:39 UTC
I was working on a latest ionic project and tried to get these icons to work but there was no luck. Then I tried the sample ionic app which is getting generated with the cli which has the ion-menu with ion icons. Those are working on the iPad browser but not inside the Webview. Tried the old ionicon:4.6.3 and that works fine.

<img width="726" alt="Screenshot 2020-05-14 at 20 13 26" src="https://user-images.githubusercontent.com/11315372/81948510-720f9d80-961f-11ea-96f9-4b472211dce6.png">

Environment:
Angular 9.0.6
Ionic 5

**Comment by himanshuarya** [comment] 2020-06-15 12:15
I can also confirm this issue. In my case, the icons appear the first time but when I force close the Ionic app and open the app again, they disappear because the SVG does not load in the Shadow Content as shown in the screenshot by @rashmendis

**Comment by rashmendis** [comment] 2020-06-15 12:42
Same for me

**Comment by himanshuarya** [comment] 2020-06-15 12:51
Another observation is that even on using a custom SVG, the SVG does not load the second time on force closing the app.

**Comment by rashmendis** [comment] 2020-06-15 14:27
Yes. Same for me

**Comment by lhaiscapyba** [comment] 2020-07-08 20:46
Same issues for me

**Comment by jdpsbh** [comment] 2020-07-16 20:47
Same here. Not only with UIWebview, also with WKWebview.

**Comment by jdpsbh** [comment] 2020-07-19 05:15
@rashmendis how did you used the old ionicon:4.6.3? Did you uninstall the 5.x and install the 4.x?

**Comment by rashmendis** [comment] 2020-07-19 05:49
Tried that but since ionicon is a dependency for ionic it will install ionicon5 with ionic 5. So I had to downgrade ionic to ionic4

**Comment by himanshuarya** [comment] 2020-10-05 04:30
@brandyscarney is anyone from the Ionic team looking into any of the ion-icon issues? It looks like none of the ion-icon issues haven't been assigned, triaged, or being investigated upon. This issue is one of the major issues in Ion-icon v5 which comes along bundled with Ionic 5. This is a blocker issue that is preventing us to upgrade from Ionic 4 to Ionic 5. Can you please get this issue resolved?

**Comment by bensperry** [comment] 2020-10-07 19:57
Hey @himanshuarya, we hear you. Can you share more information on the issue you're seeing (code sample, screenshots)?

**Comment by himanshuarya** [comment] 2020-10-08 07:30
@rashmendis Will you be able to share the code of sample ionic app in which you were able to reproduce this issue?

**Comment by rashmendis** [comment] 2020-10-08 08:38
@bensperry Just do a `ionic start myApp tabs ` and create an app with ion-icons. Then have to build the app and run it inside a uiwebview or wkwebview in iPad or an Apple device.

**Comment by bensperry** [comment] 2020-10-14 17:10
Hey @rashmendis, this is frustrating. We are unable to reproduce the issue on our end. 

Basically, we need more info. What are you using to deploy the app—are you using Capacitor or Cordova? Please share the exact steps for us to follow and be as specific as possible. This will greatly help us nail down exactly what might be going wrong more quickly.

**Comment by rashmendis** [comment] 2020-10-15 04:29
@bensperry Not using both Capacitor or Cordova. What you have to do is create a tab app using `ionic start myApp tabs`. Then you need to build the app using `ionic build --prod`. Then You have to create a iOS app with a UIWebView or WKWebView and load the ionic app which we build earlier. App is working directly on iPad Safari app without any issues but not working inside the UIWebView or WKWebView. I was testing it inside a Commercial iOS app so won't be able to share the code. But as you can see in the comments it's a common issue when we run the ionic5 app inside a iOS WebView.

**Comment by liamdebeasi** [comment] 2020-10-15 18:42
Thanks for the issue. So just using `WKWebView` or `UIWebView` is not going to be sufficient to get Ionicons loading. The reason is that when an icon SVG is loaded, it is treated as a local file, and `WKWebView` has some limitations referencing local files by itself.

The best solution here is to use a small local server to serve the files. The easiest way to do this is to use [Capacitor](https://capacitor.ionicframework.com/). You can view our [Getting Started Guide](https://capacitorjs.com/docs/getting-started#adding-capacitor-to-an-existing-web-app) to quickly integrate Capacitor into your existing app.

Can you try your app with Capacitor and let me know if it resolves the issue?

**Comment by Sagar-rr** [comment] 2021-01-06 06:45
I am facing same issue. I have used cordova in my project. I don't have time to integrate capacitor right now. So for now I am goning to use png image insted of ion-icon

**Comment by fortesp** [comment] 2021-11-15 14:33
Any news on this? <IonIcon .../> is not shown in WebView ...

**Comment by liamdebeasi** [comment] 2022-11-08 20:51
Thanks for the report and apologies for the delay. Does this issue still reproduce using the latest version of Ionicons? If so, is there a sample app I can try?

**Closed** 2022-11-22 21:09 UTC
Labels: needs: reply
