### ISSUE TITLE
copyright symbol

### ISSUE THREAD

**Issue by andrewragy** [ionic-team/ionicons#889] opened 2020-10-07 13:38 UTC
you guys should add a copy right symbol like this one
![epicentrofestival-copyright-symbol-law-author-bgz2xfosyd](https://user-images.githubusercontent.com/39835161/95338391-29e56600-08b3-11eb-85c8-84a88ce758f8.jpg)

**Comment by brandyscarney** [comment] 2022-09-27 16:29
Closing as a duplicate of #851, thank you!

**Closed by brandyscarney** 2022-09-27 16:29 UTC
Labels: type: icon request
