### ISSUE TITLE
Sorting vs filtering icon

### ISSUE THREAD

**Issue by basvdijk** [ionic-team/ionicons#896] opened 2020-10-25 11:42 UTC
Currently there is already a filter icon which shows as a funnel. However there is a difference between sorting and filtering. Therefore I would suggest to keep the funnel for filtering, and up/down arrow for sorting like https://fontawesome.com/icons/sort?style=solid&from=io

**Comment by brandyscarney** [comment] 2022-09-27 22:58
Thanks for the issue, closing as a duplicate of #424

**Closed by brandyscarney** 2022-09-27 22:58 UTC
Labels: type: icon request
