### ISSUE TITLE
Request: Icon for Birthday

### ISSUE THREAD

**Issue by cnothegger** [ionic-team/ionicons#415] opened 2016-08-13 10:56 UTC
Would be very nice if you could add icons for Birthday and Country

Good work guys!

**Comment by amandaejohnston** [comment] 2023-05-25 19:54
Thank you for the requests. We've since added `earth` and `globe` icons that should work for country selection, but we can use this to track adding a birthday icon.

**Comment by amandaejohnston** [comment] 2023-05-25 20:10
Actually, I'm going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/442. While this issue is older, the other one has more discussion and upvotes, so I think it makes sense to use that one for tracking.

**Closed by amandaejohnston** 2023-05-25 20:10 UTC
Labels: type: feature request, type: icon request
