### ISSUE TITLE
TypeScript Coding Language icon request: 

### ISSUE THREAD

**Issue by SafaroovKhan** [ionic-team/ionicons#1188] opened 2023-03-06 16:09 UTC
### Describe the Icon

Same icon with JavaScript, but for TypeScript .

**Comment by brandyscarney** [comment] 2023-04-10 17:47
Thank you for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/1185. Please upvote that issue to show your interest. 🙂

**Closed by brandyscarney** 2023-04-10 17:47 UTC
Labels: triage
