### ISSUE TITLE
V4 Web Component platform detection: Chrome device emulation support

### ISSUE THREAD

**Issue by laurentpayot** [ionic-team/ionicons#528] opened 2018-03-16 09:49 UTC
[V4 Web Component](https://github.com/ionic-team/ionicons/issues/499) does not detect the platform set by [Chrome device emulation](https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports#device-specific_mode), an essential tool for PWA developers.
On my Linux machine V4 ionicons with `name` property always autodetect `md` as the platform even when I chose iPhone emulation in Chrome. Switching to a physical iOS device to test every modification is impossible.
I guess simply detecting the platform via the browser's user agent, when used in a browser, would fix this.

**Comment by amandaejohnston** [comment] 2023-08-23 14:16
Thank you for the issue. In the time since this was posted, it looks like this behavior has been fixed; changing the emulated user agent causes the `ion-icon` to switch modes on my end. I'm going to close this out, but if you're still running into problems on the latest version of Ionicons, please open a new issue and include a minimal code reproduction. Thanks again!

**Closed by amandaejohnston** 2023-08-23 14:16 UTC
Labels: triage
