### ISSUE TITLE
Cannot Find file Specified

### ISSUE THREAD

**Issue by sapp006** [ionic-team/ionicons#353] opened 2016-02-11 18:20 UTC
When I execute the python generate script I get an error: cannot find file specified. Anyone else have this problem?

Generate Fonts
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
 with many parts BSD http://fontforge.org/license.html. Please read LICENSE.
 Based on sources from 09:10 AWST 27-Aug-2015-ML-TtfDb-D.
 Based on source from git with hash: 3d950d3cde977900e5138019a918ed671efb4449
Load Manifest, Icons: 733
New Icon:
- commercial36
- 0xf138
  New Icon:
- cutlery
- 0xf13b
  New Icon:
- food
- 0xf13c
  New Icon:
- hotel
- 0xf145
  New Icon:
- venue
- 0xf146
  Traceback (most recent call last):
  File "\ionicons-2.0.1\builder
  /scripts/generate_font.py", line 152, in <module>
  subprocess.call(['sfnt2woff', fontfile + '.ttf'])
  File "C:\Program Files (x86)\FontForgeBuilds\lib\python2.7/subprocess.py", lin
  e 522, in call
  return Popen(_popenargs, *_kwargs).wait()
  File "C:\Program Files (x86)\FontForgeBuilds\lib\python2.7/subprocess.py", lin
  e 710, in **init**
  errread, errwrite)
  File "C:\Program Files (x86)\FontForgeBuilds\lib\python2.7/subprocess.py", lin
  e 958, in _execute_child
  startupinfo)
  WindowsError: [Error 2] The system cannot find the file specified
  Generate SCSS
  Generate CSS From SCSS
  Generate Minified CSS From SCSS
  Generate LESS
  Generate Cheatsheet
  Generate component.json
  Generate composer.json
  Generate bower.json

**Comment by Trylar** [comment] 2016-03-11 12:59
+1, have same issue

**Comment by hplehn** [comment] 2016-08-11 11:49
I have the same issue on Windows 8.1.
The *.ttf file is updated correctly, but the *.woff file und the *.eot file remain unchanged.

**Comment by hplehn** [comment] 2016-08-20 08:05
Hi,
I've tried to narrow down where the problem is.
I just removed one file from the src Folder and still get the same error:

Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 11:18 AWST  7-Apr-2016-ML-TtfDb-D.
 Based on source from git with hash: 5f53fdb7999e1acf2924ae6bc0a176ccdde25e40
Traceback (most recent call last):
  File "c:\ionicons-2.0.1\builder/scripts/generate_font.py", line 152, in <module>
    subprocess.call(['sfnt2woff', fontfile + '.ttf'])
  File "C:\Program Files (x86)\FontForgeBuilds\lib\python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Program Files (x86)\FontForgeBuilds\lib\python2.7/subprocess.py", line 641, in __init__
    errread, errwrite)
  File "C:\Program Files (x86)\FontForgeBuilds\lib\python2.7/subprocess.py", line 889, in _execute_child
    startupinfo)
WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden
winClipboardIOErrorHandler!
winMultiWindowXMsgProcIOErrorHandler!
winInitMultiWindowXMsgProc - Caught IO Error.  Exiting.
winClipboardIOErrorHandler!
winClipboardProc - setjmp returned for IO Error Handler.
(EE) Server terminated with error (1). Closing log file.

(The text for WindowsError: [Error 2] is in German, it is the same as quoted above.)

I've installed the toolchain with the following versions:
- FontForge: 11:18 AWST 7-Apr-2016
- Python: 2.7.12 (v2.7.12:d33e0cf91556)
- Ruby: 2.2.5-x64
- SASS: 3.4.22
- ttfautohint: 1.5

**Comment by hplehn** [comment] 2016-08-23 17:12
I tried to run the script with Linux and get a similar error.

I installed a fresh Ubuntu 16.04.
Then I installed the toolchain with the following command:
   sudo apt-get update
   sudo apt-get install fontforge ttfautohint ruby ruby-sass

I downloaded and extracted ionicons-2.0.1

Run the script with
   python ./builder/generate.py

And again, I get a file not found error from line 152 in the script.

I tried to run the script from the /builder directory and get the identical error message.
So it seems, that something is wrong with the path...

Has anyone else this problem?

**Comment by hplehn** [comment] 2016-08-23 21:28
I think I finally found the problem.

The sfnt2woff file in the download seems to work only with Mac OS.
I replaced it by the Windows Version. You can find a download link here:
https://people.mozilla.org/~jkew/woff/

I had to change some other lines in generate_font.py:

`# subprocess.call('mv ' + fontfile + '.eotlite ' + fontfile + '.eot', shell=True)
  import shutil
  shutil.move(fontfile + '.eotlite', fontfile + '.eot')
  
  # Hint the TTF file
  # subprocess.call('ttfautohint -s -f -n ' + fontfile + '.ttf ' + fontfile + '-hinted.ttf > /dev/null 2>&1 && mv ' + fontfile + '-hinted.ttf ' + fontfile + '.ttf', shell=True)`

These changes worked for me (Windows 8.1), though I don't know, if I will need the hints in the ttf file.

**Comment by liamdebeasi** [comment] 2022-09-27 15:18
Hi everyone,

Thanks for the report and apologies for the delay. I am going to close this as the issue as Ionicons uses SVG data instead of fonts now.

**Closed by liamdebeasi** 2022-09-27 15:18 UTC
