### ISSUE TITLE
My Svg colors changed

### ISSUE THREAD

**Issue by samyfrii** [ionic-team/ionicons#612] opened 2018-09-19 16:41 UTC
Hi,
I succeded to add my Svg for facebook and Google, but the color changed on display taking the color of my primary defined in my variable.scss
![svg problem](https://user-images.githubusercontent.com/24576795/45767822-2383e300-bc33-11e8-901e-d60e18d0567c.PNG)

**Comment by peterennis** [comment] 2018-10-11 04:02
Related: https://github.com/ionic-team/ionicons/issues/589

**Comment by amandaejohnston** [comment] 2023-08-24 14:18
Thank you for the issue. I know it's been a while, but I'm going to close this due to lack of a runnable reproduction. It's possible that the `ion-icon` component had the property `color="primary"`, which would affect the color of the SVG. If this is still a problem in the latest version of Ionicons, please open a new issue and ensure the template is fully filled out. Thank you!

**Closed by amandaejohnston** 2023-08-24 14:18 UTC
Labels: triage
