### ISSUE TITLE
Search Input on website is skipping characters

### ISSUE THREAD

**Issue by Artfloriani** [ionic-team/ionicons#666] opened 2019-03-01 15:09 UTC
When searching for icons on https://ionicons.com, the search bar will skip the second character when typing quickly. 

This only happens if the input is clear and only with the second character. You also need to type with two hands, so that the second character is typed almost instantly after the first character. 

Trying to type "icicicic" will result on "iicicic":
![chrome-capture](https://user-images.githubusercontent.com/6491691/53646607-6a322c00-3c1a-11e9-84c1-432f7a087811.gif)

OS: MacOS 10.14.3
Browser: Chrome. Version 72.0.3626.119 (Official Build) (64-bit)

Happens every time I'm searching for an icon 🙂

**Comment by reduckted** [comment] 2019-03-13 10:35
Same issue here, except it's not always the second character. Sometimes it's the third or fourth character. For example, if I try to type "magnify" very quickly, it can end up as any of the following:
* mgnify
* manify
* magify

OS: Windows 10
Browser: Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by jackw01** [comment] 2019-08-13 17:22
Having this issue too on the latest versions of Firefox and Chrome on Windows 10.

**Comment by reduckted** [comment] 2019-10-20 02:22
Looks like the website now has it's own repository: https://github.com/ionic-team/ionicons-site

Perhaps this issue could be [transferred](https://help.github.com/en/articles/transferring-an-issue-to-another-repository#transferring-an-open-issue-to-another-repository) over there?

Pinging @perrygovier and @manucorporat since you're the contributors to that repository. 😄

**Comment by perrygovier** [comment] 2019-10-21 18:06
Are you able to share any more info about the error? I'm unable to reproduce it. You're sure it's not a stuck key or bad browser plugin?

**Comment by reduckted** [comment] 2019-10-22 09:21
It's definitely not an issue with the keyboard (I can reproduce it on multiple PCs), and I can reproduce it on Chrome, Firefox and Edge. Here's a recording that shows the keystrokes.
![ionicons-search](https://user-images.githubusercontent.com/10321525/67272132-4b610c80-f4ff-11e9-8888-606de5d2a7a3.gif)

And here's a recording where I've attached an `input` event listener to the search box and printed the emitted value. Quite interesting.

![ionicons-search-console](https://user-images.githubusercontent.com/10321525/67272915-cb3ba680-f500-11e9-809a-f0dfed4a3773.gif)

**Comment by perrygovier** [comment] 2019-10-22 18:21
Hmm, there's more to the story here. What language is your computer in?

**Comment by reduckted** [comment] 2019-10-23 01:29
English (United States) with a US QWERTY keyboard.

Browser console says:
```
> navigator.language
< "en-US"
> navigator.languages
> (2) ["en-US", "en"]
```

**Comment by amandaejohnston** [comment] 2023-05-31 18:46
Hi folks, I'm not able to replicate this issue on the latest version of the site, so I'm going to assume it's since been fixed and close this out. Let me know if you're still running into problems with this.

**Closed by amandaejohnston** 2023-05-31 18:46 UTC
Labels: triage
