### ISSUE TITLE
Bad documentation of logo icons (at least with unpkg)

### ISSUE THREAD

**Issue by acoreyj** [ionic-team/ionicons#540] opened 2018-05-15 21:44 UTC
Not sure if this is just unpkg issue or if used in the ionic framework as well. For the logo icons they don't work with the given code.

example:
`<ion-icon name="github"></ion-icon>` calls https://unpkg.com/ionicons@4.0.0/dist/ionicons/svg/md-github.js which 404s

What works is adding logo- prefix.
`<ion-icon name="logo-github"></ion-icon>` calls the correct  https://unpkg.com/ionicons@4.0.0/dist/ionicons/svg/logo-github.js

**Comment by ghybs** [comment] 2018-05-16 13:16
Hi,

Related documentation issue: the [usage page](https://ionicons.com/usage/) has an interesting feature that customizes the code samples with the URL fragment.
If the latter matches a known icon name, all code samples will use it instead of the default `"heart"` value.
For example: http://ionicons.com/usage/#md-save

This feature can easily be reached from the landing page:
1. Click on an icon
2. On the footer bar that appears on the bottom of the page, click on the "USAGE >" link:
![screenshot_ionicons_site](https://user-images.githubusercontent.com/12232803/40118885-32033666-592c-11e8-8e62-24eb06d40944.png)

Unfortunately, this features falls apart for `logo-` prefixed icons, e.g. http://ionicons.com/usage/#logo-github
- The 1st code sample (in "Basic usage" section) strips the `logo-` prefix, which makes the result fail: `<ion-icon name="github"></ion-icon>`
- The code samples for "Platform Continuity Outside Ionic Apps" section replace the `logo-` prefix by platform prefix (namely `ios-` and `md-`), which make the result fail: `<ion-icon name="ios-github"></ion-icon>` and `<ion-icon name="md-github"></ion-icon>`

Reproduction example: https://plnkr.co/edit/qetlRP9i2qdYYJEVKQ3w?p=preview (using ionicons v4.1.0 from unpkg)

Therefore it seems that for **logo type** icons, the **only format** that works is:
```html
<ion-icon name="logo-github"><ion-icon>
```

**Comment by acoreyj** [comment] 2018-05-16 15:25
@ghybs 

Thanks for providing all the extra great details, sounds like it is probably primarily a documentation issue rather than a code issue.

**Comment by brandyscarney** [comment] 2022-09-27 17:42
Thank you for the issue! it appears the [documentation](https://ionic.io/ionicons) has been improved since this so I am going to close this but let me know if I am missing something. 🙂

**Closed by brandyscarney** 2022-09-27 17:42 UTC
