### ISSUE TITLE
svgs are shifted upwards (not perfectly aligned)

### ISSUE THREAD

**Issue by TheComputerM** [ionic-team/ionicons#545] opened 2018-05-17 10:29 UTC
See this image please. The svg plugin is not as good as the css one.
https://ibb.co/cmZiQd

**Comment by AlQuraian** [comment] 2018-05-21 22:16
Same issue for me.. The icons seem to align poorly.

**Comment by amandaejohnston** [comment] 2023-07-13 14:23
Thank you for the issue. I'm going to close this as things are working as intended. This is a browser behavior, in that the `ion-icon` component is not as tall as the surrounding container, so it is automatically rendered at the top. I would recommend vertically centering the icon via CSS ([example](https://plnkr.co/edit/OXXXDcUml8vOwoJx?preview)). We've chosen not to apply CSS like this automatically for maximum developer flexibility.

**Closed by amandaejohnston** 2023-07-13 14:23 UTC
Labels: triage
