### ISSUE TITLE
Icon Suggestion - Telegram

### ISSUE THREAD

**Issue by fbalbinoribeiro** [ionic-team/ionicons#950] opened 2021-03-12 01:01 UTC
We have several social Ionicons for the most important message technologies. I'd like to use the Telegram icon in my app, because actually, this is one of the most popular apps in the world.

Thanks!!

**Comment by alexbleggi** [comment] 2021-04-13 17:59
Interesting, it would be usefull to have this icon in the library ...

**Comment by calvintam236** [comment] 2021-04-23 19:47
Duplicate of #338

**Comment by brandyscarney** [comment] 2022-09-27 22:03
Thanks for the issue, closing as a duplicate of #338

**Closed by brandyscarney** 2022-09-27 22:03 UTC
Labels: type: icon request
