### ISSUE TITLE
icon request: mastodon

### ISSUE THREAD

**Issue by wordshaker** [ionic-team/ionicons#1159] opened 2022-12-19 19:58 UTC
### Describe the Icon

Quite a few people have moved from the bird site to Mastodon. It would be great to have it as an icon option

![image](https://user-images.githubusercontent.com/13496774/208509451-86121a59-34ad-4e46-b1c4-20b77eeffc37.png)

### Links to Examples

- [Font Awesome equivalent](https://fontawesome.com/v5/icons/mastodon?style=brands&s=solid&f=brands)

**Comment by liamdebeasi** [comment] 2023-02-06 20:07
Thanks for the issue. I am going to close this as a duplicate of https://github.com/ionic-team/ionicons/issues/531.

**Closed by liamdebeasi** 2023-02-06 20:07 UTC
Labels: triage
