### ISSUE TITLE
Request: Behance Icon

### ISSUE THREAD

**Issue by Zaryab-Waseem** [ionic-team/ionicons#482] opened 2017-04-15 09:26 UTC
Please add an icon for Behance.

**Comment by faustobase** [comment] 2019-07-19 11:15
Hi! Any news for the behance Icon? Thanks

**Comment by marlisa31** [comment] 2020-10-07 20:31
Hi, is there an update on this in the meantime? I saw that ionicons.com lists Behance and suggests to use `<ion-icon name="logo-behance"></ion-icon>` for the behance icon. However unlike all other icons it doesn't display when I embed it into my project this way.

**Comment by amandaejohnston** [comment] 2023-05-25 20:28
Closing this out since the icon has since been added under `logo-behance`. If you're having trouble getting the icon to display with the latest version of Ionicons, please open a separate issue with a link to a minimal reproduction app. Thank you!

**Closed by amandaejohnston** 2023-05-25 20:28 UTC
Labels: type: feature request, type: icon request
