### ISSUE TITLE
icon request: quotation mark icon

### ISSUE THREAD

**Issue by Emojii911** [ionic-team/ionicons#1321] opened 2024-01-23 17:24 UTC
### Describe the Icon

The quotation mark (") that identify direct speech, a quotation, or a phrase.

### Links to Examples

https://www.iconfinder.com/icons/550002/quotation_quote_reference_speech_testimonial_text_icon

**Comment by mapsandapps** [comment] 2024-01-24 15:47
Thanks for the icon request. I'm going to close this as a duplicate of #1241.

**Closed by mapsandapps** 2024-01-24 15:47 UTC
Labels: type: icon request
