### ISSUE TITLE
incorrect icon: Soundcloud icon is currently missing

### ISSUE THREAD

**Issue by james-gulland** [ionic-team/ionicons#1205] opened 2023-04-18 08:24 UTC
### Describe the Issue

Trying to use the defined soundcloud icon but it appears the link is missing.  I would be hugely grateful if someone could fix as I have an assignment due in at the end of the week and would be lovely to be able to use these amazing icons!

<ion-icon name="logo-soundcloud"></ion-icon>

### Expected Behavior

The expected link to work: `<ion-icon name="logo-soundcloud"></ion-icon>`

**Comment by mapsandapps** [comment] 2023-04-18 14:23
Thank you for the report.

It sounds like this may be a duplicate of #1032. If you are seeing a "Failed to construct 'URL'" error, the workaround provided there may work for you as well:

```jsx
import { logoSoundcloud } from "ionicons/icons";

<ion-icon :icon="logoSoundcloud"></ion-icon>
```

Please let us know if that works for you. If it does not work, please provide a reproduction and more information about any errors you are seeing in the console.

**Comment by james-gulland** [comment] 2023-04-19 08:19
Hi,

I believe the problem is that the resource is not there in the first place,
I am getting a 404 error, where other icons work fine.  I think the file is
just missing, so would be great if it could be re-uploaded!

[image: image.png]

Thanks

James

**Comment by amandaejohnston** [comment] 2023-06-02 16:27
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionicons, please open a new issue. Thank you!

**Closed by amandaejohnston** 2023-06-02 16:27 UTC
Labels: ionitron: needs reproduction
