### ISSUE TITLE
CDN Issue

### ISSUE THREAD

**Issue by Black-Blaze** [ionic-team/ionicons#974] opened 2021-05-20 16:25 UTC
The Package For Ionicons Is No Longer Present On Unpkg.

I Used The Link And Went To The Root Of The CDN, The File Was Missing

**Comment by coders-sohan** [comment] 2021-05-21 14:41
I am also facing this problem.

It showing "    Loading failed for the <script> with source “https://unpkg.com/ionicons@5.5.1/dist/ionicons.js”.    "

**Comment by calvintam236** [comment] 2021-05-23 07:24
duplicate of #971

**Comment by liamdebeasi** [comment] 2021-06-17 14:08
Hi everyone,

This has been resolved via https://github.com/ionic-team/ionicons/pull/982, and with Ionicons v5.5.2 the `ionicons.js` file should be working again.

Stencil 1 had a deprecated loader that, when used, automatically added `module` and `nomodule` script tags to your web page. In Stencil 2 that loader was removed in favor of adding the `module` and `nomodule` script tags manually.

Ionicons v5.5 updated its internals to Stencil 2 to better support the custom elements bundle functionality, but in doing so we lost the deprecated loader.

I re-added the deprecated loader so that there is no breaking change in Ionicons v5 functionality, but this loader will be removed in Ionicons v6.

I have updated the usage on the Ionicons website to show the new installation code that we recommend: https://ionic.io/ionicons/usage The installation code that was previously recommended will be supported for all of Ionicons v5.

**Closed by liamdebeasi** 2021-06-17 14:08 UTC
